Dependencies clean-up 🧼
tidymodels/censored pull request #193
Opened 2022-06-15 20:08 UTC by hfrick

closes #39

- removes `riskRegression` which is not used
- for suggested packages: moves from functions via `::` to making and evaluating a call via rlang
- guards tests for suggested packages

A question: Could/Should I move `mboost` to Suggests? The only instance (outside of tests) of using it via `::` is in an expression:
https://github.com/tidymodels/censored/blob/24015a6d45fe5c4b8a9f0c083522e09a57bd7685/R/boost_tree_data.R#L76

2022-06-16 13:07 UTC, DavisVaughan requested changes

2022-06-16 13:07 UTC, DavisVaughan commented on R/proportional_hazards_data.R
> +    stratify_surv_call <- rlang::call2("stratifySurv", .ns  = "glmnet")
If a package is in Suggests, like glmnet, you shouldn't have to do this.

You only have to do this if the package isn't listed as a dependency of your package at all

2022-06-16 13:07 UTC, DavisVaughan commented on R/boost_tree.R
> +  survFit_call <- rlang::call2("survFit", .ns = "mboost")
This is in Imports, you definitely dont need to use the call2 form here

2022-06-16 13:07 UTC, DavisVaughan commented on R/proportional_hazards_data.R
> +    stratify_surv_call <- rlang::call2("stratifySurv", .ns  = "glmnet")
Like in parsnip we have a `rand_forest()` engine for the `"randomForest"` package. That isn't listed as a dependency of parsnip at all though, so we have to use call2 there

2022-06-16 13:07 UTC, DavisVaughan commented on R/boost_tree.R
> +  survFit_call <- rlang::call2("survFit", .ns = "mboost")
Even if you move it to suggests, you dont need to use call2

2022-06-17 13:46 UTC, hfrick commented
okay, so then I'll not make the code unnecessarily fancier and leave additional moves to `call2()` out 👍  

re guarding the use of suggested packages in tests: I'll also leave that for now given https://r-pkgs.org/description.html#suggested-packages-and-tests says
> As with vignettes, the tidyverse team does not usually guard the use of a suggested package in a test. In general, for vignettes and tests, we assume all suggested packages are available.

I'll close this PR and make a new one that only removes `riskRegression`.

If we ever need to move any package out of the official dependencies, we can come back to this.

2022-06-17 13:46 UTC, closed without merging